### ISSUE TITLE
Crash on server start with v3.4.5

### ISSUE THREAD

**Issue by tamasys** [Skidamek/AutoModpack#158]
### Bug description

After updating to v3.4.5, server can't start, crashing with error
```
Caused by: java.lang.NullPointerException: Cannot read field "generateModpackOnStart" because "pl.skidam.automodpack.GlobalVariables.serverConfig" is null
    at pl.skidam.automodpack.AutoModpack.onInitialize(AutoModpack.java:55) ~[transformed-mod-automodpack.i0:0/:?]
```

### Steps to reproduce

1. Update mod to v3.4.5
2. Attempt to start server

### Expected behavior

Server starts

### Actual behavior

Server crashes

### Relevant logs

https://gist.github.com/tamasys/f05bbd3c04cc090e3c18ac78be10d009

### Minecraft & Mod Loader versions

1.19.2 quilt 0.19.2

### Operating system

n/a

### AutoModpack version

3.4.5

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
fixed in 3.5.0

**Comment by limejet** [comment]
Unfortunately, the problem still seems to exist in 3.5.0. The object in question has just moved to `
pl.skidam.automodpack_common.GlobalVariables.serverConfig`.
```java
[19:33:03] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'automodpack'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:65) ~[quilt-loader-0.20.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [transformed-mod-minecraft.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) [quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) [quilt-loader-0.20.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.20.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66) [quilt-loader-0.20.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "generateModpackOnStart" because "pl.skidam.automodpack_common.GlobalVariables.serverConfig" is null
	at pl.skidam.automodpack.AutoModpack.onInitialize(AutoModpack.java:58) ~[transformed-mod-automodpack.i0:0/:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(Unknown Source) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy29.onInitialize(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.20.2.jar:?]
	... 16 more
```

MC 1.19.2, Quilt 0.19.3.

I see in the changelog that 3.5.0 had some problems running on quilt, is this one of the known issues?

**Comment by Skidamek** [comment]
Yes, with quilt currently there is an issue that it doesn't want to load automodpack's dependencies, no idea why... You could create separate issue for that to track it.
