### ISSUE TITLE
Cannot connect to server - NeoForge 1.21.1

### ISSUE THREAD

**Issue by spunchbop121** [Skidamek/AutoModpack#383]
### Bug description

https://mclo.gs/zl7CEq5

Cannot connect to server

### Steps to reproduce

1. Launch the game
2. Add server
3. Get the error message

### Minecraft & Mod Loader versions

1.21.1

### Minecraft launcher

Prism

### Operating system

win11

### AutoModpack version

automodpack-mc1.21.1-neoforge-4.0.0-beta36.jar + dev build from latest issue page

### Check list

- [x] I have verified that the issue persists in the latest version of the mod.
- [x] I have searched the existing issues and confirmed that this is not a duplicate.
- [x] I have provided all the necessary information to reproduce the issue.
- [x] I have verified that the issue does not occur without the AutoModpack - Ignore if you are reporting a mod conflict issue.

**Comment by spunchbop121** [comment]
Fixed. Thanks

**Comment by Skidamek** [comment]
No, its not fixed, i would like to know why does it happen in the first place.
Could you send a server log from when it breaks?
